// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: lux.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DayNightMode information
type GetDayNightModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayNightModeRequest) Reset() {
	*x = GetDayNightModeRequest{}
	mi := &file_lux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayNightModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayNightModeRequest) ProtoMessage() {}

func (x *GetDayNightModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayNightModeRequest.ProtoReflect.Descriptor instead.
func (*GetDayNightModeRequest) Descriptor() ([]byte, []int) {
	return file_lux_proto_rawDescGZIP(), []int{0}
}

type GetDayNightModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayNightMode  string                 `protobuf:"bytes,1,opt,name=dayNightMode,proto3" json:"dayNightMode,omitempty"` // Day or Night mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayNightModeResponse) Reset() {
	*x = GetDayNightModeResponse{}
	mi := &file_lux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayNightModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayNightModeResponse) ProtoMessage() {}

func (x *GetDayNightModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayNightModeResponse.ProtoReflect.Descriptor instead.
func (*GetDayNightModeResponse) Descriptor() ([]byte, []int) {
	return file_lux_proto_rawDescGZIP(), []int{1}
}

func (x *GetDayNightModeResponse) GetDayNightMode() string {
	if x != nil {
		return x.DayNightMode
	}
	return ""
}

var File_lux_proto protoreflect.FileDescriptor

const file_lux_proto_rawDesc = "" +
	"\n" +
	"\tlux.proto\x12\rcanf22g2.grpc\x1a\x1cgoogle/api/annotations.proto\"\x18\n" +
	"\x16GetDayNightModeRequest\"=\n" +
	"\x17GetDayNightModeResponse\x12\"\n" +
	"\fdayNightMode\x18\x01 \x01(\tR\fdayNightMode2\x84\x01\n" +
	"\n" +
	"LuxService\x12v\n" +
	"\x0fGetDayNightMode\x12%.canf22g2.grpc.GetDayNightModeRequest\x1a&.canf22g2.grpc.GetDayNightModeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/lux/modeB\x0fZ\rcanf22g2/grpcb\x06proto3"

var (
	file_lux_proto_rawDescOnce sync.Once
	file_lux_proto_rawDescData []byte
)

func file_lux_proto_rawDescGZIP() []byte {
	file_lux_proto_rawDescOnce.Do(func() {
		file_lux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lux_proto_rawDesc), len(file_lux_proto_rawDesc)))
	})
	return file_lux_proto_rawDescData
}

var file_lux_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lux_proto_goTypes = []any{
	(*GetDayNightModeRequest)(nil),  // 0: canf22g2.grpc.GetDayNightModeRequest
	(*GetDayNightModeResponse)(nil), // 1: canf22g2.grpc.GetDayNightModeResponse
}
var file_lux_proto_depIdxs = []int32{
	0, // 0: canf22g2.grpc.LuxService.GetDayNightMode:input_type -> canf22g2.grpc.GetDayNightModeRequest
	1, // 1: canf22g2.grpc.LuxService.GetDayNightMode:output_type -> canf22g2.grpc.GetDayNightModeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lux_proto_init() }
func file_lux_proto_init() {
	if File_lux_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lux_proto_rawDesc), len(file_lux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lux_proto_goTypes,
		DependencyIndexes: file_lux_proto_depIdxs,
		MessageInfos:      file_lux_proto_msgTypes,
	}.Build()
	File_lux_proto = out.File
	file_lux_proto_goTypes = nil
	file_lux_proto_depIdxs = nil
}
