// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: system.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AllSystemInfo
type GetAllSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSystemInfoRequest) Reset() {
	*x = GetAllSystemInfoRequest{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSystemInfoRequest) ProtoMessage() {}

func (x *GetAllSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAllSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

type GetAllSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FWVersion     string                 `protobuf:"bytes,1,opt,name=FWVersion,proto3" json:"FWVersion,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
	SerialNo      string                 `protobuf:"bytes,3,opt,name=SerialNo,proto3" json:"SerialNo,omitempty"`
	SKUName       string                 `protobuf:"bytes,4,opt,name=SKUName,proto3" json:"SKUName,omitempty"`
	DeviceName    string                 `protobuf:"bytes,5,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	MAC           string                 `protobuf:"bytes,6,opt,name=MAC,proto3" json:"MAC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSystemInfoResponse) Reset() {
	*x = GetAllSystemInfoResponse{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSystemInfoResponse) ProtoMessage() {}

func (x *GetAllSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAllSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllSystemInfoResponse) GetFWVersion() string {
	if x != nil {
		return x.FWVersion
	}
	return ""
}

func (x *GetAllSystemInfoResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *GetAllSystemInfoResponse) GetSerialNo() string {
	if x != nil {
		return x.SerialNo
	}
	return ""
}

func (x *GetAllSystemInfoResponse) GetSKUName() string {
	if x != nil {
		return x.SKUName
	}
	return ""
}

func (x *GetAllSystemInfoResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GetAllSystemInfoResponse) GetMAC() string {
	if x != nil {
		return x.MAC
	}
	return ""
}

// SetTime
type SetTimeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time format: 2024-08-22T15:00:02.574UTC+08:00 or 2024-08-22T15:00:02.574UTC+08:00DST
	Time          string `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTimeRequest) Reset() {
	*x = SetTimeRequest{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeRequest) ProtoMessage() {}

func (x *SetTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeRequest.ProtoReflect.Descriptor instead.
func (*SetTimeRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *SetTimeRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type SetTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTimeResponse) Reset() {
	*x = SetTimeResponse{}
	mi := &file_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeResponse) ProtoMessage() {}

func (x *SetTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeResponse.ProtoReflect.Descriptor instead.
func (*SetTimeResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *SetTimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RunCmd
type RunCmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCmdRequest) Reset() {
	*x = RunCmdRequest{}
	mi := &file_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCmdRequest) ProtoMessage() {}

func (x *RunCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCmdRequest.ProtoReflect.Descriptor instead.
func (*RunCmdRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{4}
}

func (x *RunCmdRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type RunCmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCmdResponse) Reset() {
	*x = RunCmdResponse{}
	mi := &file_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCmdResponse) ProtoMessage() {}

func (x *RunCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCmdResponse.ProtoReflect.Descriptor instead.
func (*RunCmdResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{5}
}

func (x *RunCmdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAlprRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlprRequest) Reset() {
	*x = GetAlprRequest{}
	mi := &file_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlprRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlprRequest) ProtoMessage() {}

func (x *GetAlprRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlprRequest.ProtoReflect.Descriptor instead.
func (*GetAlprRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{6}
}

func (x *GetAlprRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type GetAlprResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlprResponse) Reset() {
	*x = GetAlprResponse{}
	mi := &file_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlprResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlprResponse) ProtoMessage() {}

func (x *GetAlprResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlprResponse.ProtoReflect.Descriptor instead.
func (*GetAlprResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{7}
}

func (x *GetAlprResponse) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type SetAlprRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlprRequest) Reset() {
	*x = SetAlprRequest{}
	mi := &file_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlprRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlprRequest) ProtoMessage() {}

func (x *SetAlprRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlprRequest.ProtoReflect.Descriptor instead.
func (*SetAlprRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{8}
}

func (x *SetAlprRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type SetAlprResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlprResponse) Reset() {
	*x = SetAlprResponse{}
	mi := &file_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlprResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlprResponse) ProtoMessage() {}

func (x *SetAlprResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlprResponse.ProtoReflect.Descriptor instead.
func (*SetAlprResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{9}
}

func (x *SetAlprResponse) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\rcanf22g2.grpc\x1a\x1cgoogle/api/annotations.proto\"\x19\n" +
	"\x17GetAllSystemInfoRequest\"\xb4\x01\n" +
	"\x18GetAllSystemInfoResponse\x12\x1c\n" +
	"\tFWVersion\x18\x01 \x01(\tR\tFWVersion\x12\x12\n" +
	"\x04Time\x18\x02 \x01(\tR\x04Time\x12\x1a\n" +
	"\bSerialNo\x18\x03 \x01(\tR\bSerialNo\x12\x18\n" +
	"\aSKUName\x18\x04 \x01(\tR\aSKUName\x12\x1e\n" +
	"\n" +
	"DeviceName\x18\x05 \x01(\tR\n" +
	"DeviceName\x12\x10\n" +
	"\x03MAC\x18\x06 \x01(\tR\x03MAC\"$\n" +
	"\x0eSetTimeRequest\x12\x12\n" +
	"\x04Time\x18\x01 \x01(\tR\x04Time\"+\n" +
	"\x0fSetTimeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\rRunCmdRequest\x12\x10\n" +
	"\x03Cmd\x18\x01 \x01(\tR\x03Cmd\"*\n" +
	"\x0eRunCmdResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x0eGetAlprRequest\x12\x1c\n" +
	"\tisEnabled\x18\x01 \x01(\bR\tisEnabled\"/\n" +
	"\x0fGetAlprResponse\x12\x1c\n" +
	"\tisEnabled\x18\x01 \x01(\bR\tisEnabled\".\n" +
	"\x0eSetAlprRequest\x12\x1c\n" +
	"\tisEnabled\x18\x01 \x01(\bR\tisEnabled\"/\n" +
	"\x0fSetAlprResponse\x12\x1c\n" +
	"\tisEnabled\x18\x01 \x01(\bR\tisEnabled2\xbb\x04\n" +
	"\x11DeviceInfoService\x12|\n" +
	"\x10GetAllSystemInfo\x12&.canf22g2.grpc.GetAllSystemInfoRequest\x1a'.canf22g2.grpc.GetAllSystemInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/system/info\x12d\n" +
	"\aSetTime\x12\x1d.canf22g2.grpc.SetTimeRequest\x1a\x1e.canf22g2.grpc.SetTimeResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/system/time\x12_\n" +
	"\x06RunCmd\x12\x1c.canf22g2.grpc.RunCmdRequest\x1a\x1d.canf22g2.grpc.RunCmdResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/system/rc\x12n\n" +
	"\rGetAlprStatus\x12\x1d.canf22g2.grpc.GetAlprRequest\x1a\x1e.canf22g2.grpc.GetAlprResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/system/alpr/status\x12q\n" +
	"\rSetAlprStatus\x12\x1d.canf22g2.grpc.SetAlprRequest\x1a\x1e.canf22g2.grpc.SetAlprResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/system/alpr/statusB\x0fZ\rcanf22g2/grpcb\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_system_proto_goTypes = []any{
	(*GetAllSystemInfoRequest)(nil),  // 0: canf22g2.grpc.GetAllSystemInfoRequest
	(*GetAllSystemInfoResponse)(nil), // 1: canf22g2.grpc.GetAllSystemInfoResponse
	(*SetTimeRequest)(nil),           // 2: canf22g2.grpc.SetTimeRequest
	(*SetTimeResponse)(nil),          // 3: canf22g2.grpc.SetTimeResponse
	(*RunCmdRequest)(nil),            // 4: canf22g2.grpc.RunCmdRequest
	(*RunCmdResponse)(nil),           // 5: canf22g2.grpc.RunCmdResponse
	(*GetAlprRequest)(nil),           // 6: canf22g2.grpc.GetAlprRequest
	(*GetAlprResponse)(nil),          // 7: canf22g2.grpc.GetAlprResponse
	(*SetAlprRequest)(nil),           // 8: canf22g2.grpc.SetAlprRequest
	(*SetAlprResponse)(nil),          // 9: canf22g2.grpc.SetAlprResponse
}
var file_system_proto_depIdxs = []int32{
	0, // 0: canf22g2.grpc.DeviceInfoService.GetAllSystemInfo:input_type -> canf22g2.grpc.GetAllSystemInfoRequest
	2, // 1: canf22g2.grpc.DeviceInfoService.SetTime:input_type -> canf22g2.grpc.SetTimeRequest
	4, // 2: canf22g2.grpc.DeviceInfoService.RunCmd:input_type -> canf22g2.grpc.RunCmdRequest
	6, // 3: canf22g2.grpc.DeviceInfoService.GetAlprStatus:input_type -> canf22g2.grpc.GetAlprRequest
	8, // 4: canf22g2.grpc.DeviceInfoService.SetAlprStatus:input_type -> canf22g2.grpc.SetAlprRequest
	1, // 5: canf22g2.grpc.DeviceInfoService.GetAllSystemInfo:output_type -> canf22g2.grpc.GetAllSystemInfoResponse
	3, // 6: canf22g2.grpc.DeviceInfoService.SetTime:output_type -> canf22g2.grpc.SetTimeResponse
	5, // 7: canf22g2.grpc.DeviceInfoService.RunCmd:output_type -> canf22g2.grpc.RunCmdResponse
	7, // 8: canf22g2.grpc.DeviceInfoService.GetAlprStatus:output_type -> canf22g2.grpc.GetAlprResponse
	9, // 9: canf22g2.grpc.DeviceInfoService.SetAlprStatus:output_type -> canf22g2.grpc.SetAlprResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
