// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: network.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Network
type GetIPv4Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPv4Request) Reset() {
	*x = GetIPv4Request{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPv4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPv4Request) ProtoMessage() {}

func (x *GetIPv4Request) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPv4Request.ProtoReflect.Descriptor instead.
func (*GetIPv4Request) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

type GetIPv4Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPv4          string                 `protobuf:"bytes,1,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPv4Response) Reset() {
	*x = GetIPv4Response{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPv4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPv4Response) ProtoMessage() {}

func (x *GetIPv4Response) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPv4Response.ProtoReflect.Descriptor instead.
func (*GetIPv4Response) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *GetIPv4Response) GetIPv4() string {
	if x != nil {
		return x.IPv4
	}
	return ""
}

type UpdateIPv4Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPv4          string                 `protobuf:"bytes,1,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIPv4Request) Reset() {
	*x = UpdateIPv4Request{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIPv4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIPv4Request) ProtoMessage() {}

func (x *UpdateIPv4Request) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIPv4Request.ProtoReflect.Descriptor instead.
func (*UpdateIPv4Request) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateIPv4Request) GetIPv4() string {
	if x != nil {
		return x.IPv4
	}
	return ""
}

type UpdateIPv4Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIPv4Response) Reset() {
	*x = UpdateIPv4Response{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIPv4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIPv4Response) ProtoMessage() {}

func (x *UpdateIPv4Response) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIPv4Response.ProtoReflect.Descriptor instead.
func (*UpdateIPv4Response) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateIPv4Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetIPv6Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPv6Request) Reset() {
	*x = GetIPv6Request{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPv6Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPv6Request) ProtoMessage() {}

func (x *GetIPv6Request) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPv6Request.ProtoReflect.Descriptor instead.
func (*GetIPv6Request) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

type GetIPv6Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPv6          string                 `protobuf:"bytes,1,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPv6Response) Reset() {
	*x = GetIPv6Response{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPv6Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPv6Response) ProtoMessage() {}

func (x *GetIPv6Response) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPv6Response.ProtoReflect.Descriptor instead.
func (*GetIPv6Response) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *GetIPv6Response) GetIPv6() string {
	if x != nil {
		return x.IPv6
	}
	return ""
}

type GetDHCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDHCPRequest) Reset() {
	*x = GetDHCPRequest{}
	mi := &file_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDHCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDHCPRequest) ProtoMessage() {}

func (x *GetDHCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDHCPRequest.ProtoReflect.Descriptor instead.
func (*GetDHCPRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

type GetDHCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DHCP          bool                   `protobuf:"varint,1,opt,name=DHCP,proto3" json:"DHCP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDHCPResponse) Reset() {
	*x = GetDHCPResponse{}
	mi := &file_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDHCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDHCPResponse) ProtoMessage() {}

func (x *GetDHCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDHCPResponse.ProtoReflect.Descriptor instead.
func (*GetDHCPResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7}
}

func (x *GetDHCPResponse) GetDHCP() bool {
	if x != nil {
		return x.DHCP
	}
	return false
}

type UpdateDHCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DHCP          bool                   `protobuf:"varint,1,opt,name=DHCP,proto3" json:"DHCP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDHCPRequest) Reset() {
	*x = UpdateDHCPRequest{}
	mi := &file_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDHCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDHCPRequest) ProtoMessage() {}

func (x *UpdateDHCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDHCPRequest.ProtoReflect.Descriptor instead.
func (*UpdateDHCPRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDHCPRequest) GetDHCP() bool {
	if x != nil {
		return x.DHCP
	}
	return false
}

type UpdateDHCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDHCPResponse) Reset() {
	*x = UpdateDHCPResponse{}
	mi := &file_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDHCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDHCPResponse) ProtoMessage() {}

func (x *UpdateDHCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDHCPResponse.ProtoReflect.Descriptor instead.
func (*UpdateDHCPResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDHCPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetAllNetworkInfo combines all network information into a single response
type GetAllNetworkInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNetworkInfoRequest) Reset() {
	*x = GetAllNetworkInfoRequest{}
	mi := &file_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNetworkInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNetworkInfoRequest) ProtoMessage() {}

func (x *GetAllNetworkInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNetworkInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAllNetworkInfoRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{10}
}

type GetAllNetworkInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPv4          string                 `protobuf:"bytes,1,opt,name=IPv4,proto3" json:"IPv4,omitempty"`
	IPv6          string                 `protobuf:"bytes,2,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNetworkInfoResponse) Reset() {
	*x = GetAllNetworkInfoResponse{}
	mi := &file_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNetworkInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNetworkInfoResponse) ProtoMessage() {}

func (x *GetAllNetworkInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNetworkInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAllNetworkInfoResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllNetworkInfoResponse) GetIPv4() string {
	if x != nil {
		return x.IPv4
	}
	return ""
}

func (x *GetAllNetworkInfoResponse) GetIPv6() string {
	if x != nil {
		return x.IPv6
	}
	return ""
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\rcanf22g2.grpc\x1a\x1cgoogle/api/annotations.proto\"\x10\n" +
	"\x0eGetIPv4Request\"%\n" +
	"\x0fGetIPv4Response\x12\x12\n" +
	"\x04IPv4\x18\x01 \x01(\tR\x04IPv4\"'\n" +
	"\x11UpdateIPv4Request\x12\x12\n" +
	"\x04IPv4\x18\x01 \x01(\tR\x04IPv4\".\n" +
	"\x12UpdateIPv4Response\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"\x10\n" +
	"\x0eGetIPv6Request\"%\n" +
	"\x0fGetIPv6Response\x12\x12\n" +
	"\x04IPv6\x18\x01 \x01(\tR\x04IPv6\"\x10\n" +
	"\x0eGetDHCPRequest\"%\n" +
	"\x0fGetDHCPResponse\x12\x12\n" +
	"\x04DHCP\x18\x01 \x01(\bR\x04DHCP\"'\n" +
	"\x11UpdateDHCPRequest\x12\x12\n" +
	"\x04DHCP\x18\x01 \x01(\bR\x04DHCP\".\n" +
	"\x12UpdateDHCPResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"\x1a\n" +
	"\x18GetAllNetworkInfoRequest\"C\n" +
	"\x19GetAllNetworkInfoResponse\x12\x12\n" +
	"\x04IPv4\x18\x01 \x01(\tR\x04IPv4\x12\x12\n" +
	"\x04IPv6\x18\x02 \x01(\tR\x04IPv62\xcc\x03\n" +
	"\x12NetworkInfoService\x12b\n" +
	"\aGetIPv4\x12\x1d.canf22g2.grpc.GetIPv4Request\x1a\x1e.canf22g2.grpc.GetIPv4Response\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/network/ipv4\x12n\n" +
	"\n" +
	"UpdateIPv4\x12 .canf22g2.grpc.UpdateIPv4Request\x1a!.canf22g2.grpc.UpdateIPv4Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/network/ipv4\x12b\n" +
	"\aGetIPv6\x12\x1d.canf22g2.grpc.GetIPv6Request\x1a\x1e.canf22g2.grpc.GetIPv6Response\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/network/ipv6\x12~\n" +
	"\x11GetAllNetworkInfo\x12'.canf22g2.grpc.GetAllNetworkInfoRequest\x1a(.canf22g2.grpc.GetAllNetworkInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/network/ipB\x0fZ\rcanf22g2/grpcb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_network_proto_goTypes = []any{
	(*GetIPv4Request)(nil),            // 0: canf22g2.grpc.GetIPv4Request
	(*GetIPv4Response)(nil),           // 1: canf22g2.grpc.GetIPv4Response
	(*UpdateIPv4Request)(nil),         // 2: canf22g2.grpc.UpdateIPv4Request
	(*UpdateIPv4Response)(nil),        // 3: canf22g2.grpc.UpdateIPv4Response
	(*GetIPv6Request)(nil),            // 4: canf22g2.grpc.GetIPv6Request
	(*GetIPv6Response)(nil),           // 5: canf22g2.grpc.GetIPv6Response
	(*GetDHCPRequest)(nil),            // 6: canf22g2.grpc.GetDHCPRequest
	(*GetDHCPResponse)(nil),           // 7: canf22g2.grpc.GetDHCPResponse
	(*UpdateDHCPRequest)(nil),         // 8: canf22g2.grpc.UpdateDHCPRequest
	(*UpdateDHCPResponse)(nil),        // 9: canf22g2.grpc.UpdateDHCPResponse
	(*GetAllNetworkInfoRequest)(nil),  // 10: canf22g2.grpc.GetAllNetworkInfoRequest
	(*GetAllNetworkInfoResponse)(nil), // 11: canf22g2.grpc.GetAllNetworkInfoResponse
}
var file_network_proto_depIdxs = []int32{
	0,  // 0: canf22g2.grpc.NetworkInfoService.GetIPv4:input_type -> canf22g2.grpc.GetIPv4Request
	2,  // 1: canf22g2.grpc.NetworkInfoService.UpdateIPv4:input_type -> canf22g2.grpc.UpdateIPv4Request
	4,  // 2: canf22g2.grpc.NetworkInfoService.GetIPv6:input_type -> canf22g2.grpc.GetIPv6Request
	10, // 3: canf22g2.grpc.NetworkInfoService.GetAllNetworkInfo:input_type -> canf22g2.grpc.GetAllNetworkInfoRequest
	1,  // 4: canf22g2.grpc.NetworkInfoService.GetIPv4:output_type -> canf22g2.grpc.GetIPv4Response
	3,  // 5: canf22g2.grpc.NetworkInfoService.UpdateIPv4:output_type -> canf22g2.grpc.UpdateIPv4Response
	5,  // 6: canf22g2.grpc.NetworkInfoService.GetIPv6:output_type -> canf22g2.grpc.GetIPv6Response
	11, // 7: canf22g2.grpc.NetworkInfoService.GetAllNetworkInfo:output_type -> canf22g2.grpc.GetAllNetworkInfoResponse
	4,  // [4:8] is the sub-list for method output_type
	0,  // [0:4] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
