// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: fota.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FotaService_Fota_FullMethodName = "/canf22g2.grpc.FotaService/Fota"
)

// FotaServiceClient is the client API for FotaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FotaServiceClient interface {
	Fota(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FotaStatus], error)
}

type fotaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFotaServiceClient(cc grpc.ClientConnInterface) FotaServiceClient {
	return &fotaServiceClient{cc}
}

func (c *fotaServiceClient) Fota(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FotaStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FotaService_ServiceDesc.Streams[0], FotaService_Fota_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FotaStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FotaService_FotaClient = grpc.BidiStreamingClient[FileChunk, FotaStatus]

// FotaServiceServer is the server API for FotaService service.
// All implementations must embed UnimplementedFotaServiceServer
// for forward compatibility.
type FotaServiceServer interface {
	Fota(grpc.BidiStreamingServer[FileChunk, FotaStatus]) error
	mustEmbedUnimplementedFotaServiceServer()
}

// UnimplementedFotaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFotaServiceServer struct{}

func (UnimplementedFotaServiceServer) Fota(grpc.BidiStreamingServer[FileChunk, FotaStatus]) error {
	return status.Errorf(codes.Unimplemented, "method Fota not implemented")
}
func (UnimplementedFotaServiceServer) mustEmbedUnimplementedFotaServiceServer() {}
func (UnimplementedFotaServiceServer) testEmbeddedByValue()                     {}

// UnsafeFotaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FotaServiceServer will
// result in compilation errors.
type UnsafeFotaServiceServer interface {
	mustEmbedUnimplementedFotaServiceServer()
}

func RegisterFotaServiceServer(s grpc.ServiceRegistrar, srv FotaServiceServer) {
	// If the following call pancis, it indicates UnimplementedFotaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FotaService_ServiceDesc, srv)
}

func _FotaService_Fota_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FotaServiceServer).Fota(&grpc.GenericServerStream[FileChunk, FotaStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FotaService_FotaServer = grpc.BidiStreamingServer[FileChunk, FotaStatus]

// FotaService_ServiceDesc is the grpc.ServiceDesc for FotaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FotaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "canf22g2.grpc.FotaService",
	HandlerType: (*FotaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fota",
			Handler:       _FotaService_Fota_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fota.proto",
}
