// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: ioctrl.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_RED   Color = 0
	Color_GREEN Color = 1
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "RED",
		1: "GREEN",
	}
	Color_value = map[string]int32{
		"RED":   0,
		"GREEN": 1,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_ioctrl_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_ioctrl_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{0}
}

type SetLEDsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusLedColor Color                  `protobuf:"varint,1,opt,name=statusLedColor,proto3,enum=canf22g2.grpc.Color" json:"statusLedColor,omitempty"` // set status LED color
	RecLedOn       bool                   `protobuf:"varint,2,opt,name=recLedOn,proto3" json:"recLedOn,omitempty"`                                      // on/off recording led (true/false)
	Channel        int32                  `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`                                        // channel 0 or 1
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetLEDsRequest) Reset() {
	*x = SetLEDsRequest{}
	mi := &file_ioctrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLEDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLEDsRequest) ProtoMessage() {}

func (x *SetLEDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLEDsRequest.ProtoReflect.Descriptor instead.
func (*SetLEDsRequest) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{0}
}

func (x *SetLEDsRequest) GetStatusLedColor() Color {
	if x != nil {
		return x.StatusLedColor
	}
	return Color_RED
}

func (x *SetLEDsRequest) GetRecLedOn() bool {
	if x != nil {
		return x.RecLedOn
	}
	return false
}

func (x *SetLEDsRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type SetLEDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLEDsResponse) Reset() {
	*x = SetLEDsResponse{}
	mi := &file_ioctrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLEDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLEDsResponse) ProtoMessage() {}

func (x *SetLEDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLEDsResponse.ProtoReflect.Descriptor instead.
func (*SetLEDsResponse) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{1}
}

func (x *SetLEDsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLEDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       int32                  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"` // specify which channel to query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLEDsRequest) Reset() {
	*x = GetLEDsRequest{}
	mi := &file_ioctrl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLEDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLEDsRequest) ProtoMessage() {}

func (x *GetLEDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLEDsRequest.ProtoReflect.Descriptor instead.
func (*GetLEDsRequest) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{2}
}

func (x *GetLEDsRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type GetLEDsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusLedColor Color                  `protobuf:"varint,1,opt,name=statusLedColor,proto3,enum=canf22g2.grpc.Color" json:"statusLedColor,omitempty"`
	RecLedOn       bool                   `protobuf:"varint,2,opt,name=recLedOn,proto3" json:"recLedOn,omitempty"`
	Channel        int32                  `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLEDsResponse) Reset() {
	*x = GetLEDsResponse{}
	mi := &file_ioctrl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLEDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLEDsResponse) ProtoMessage() {}

func (x *GetLEDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioctrl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLEDsResponse.ProtoReflect.Descriptor instead.
func (*GetLEDsResponse) Descriptor() ([]byte, []int) {
	return file_ioctrl_proto_rawDescGZIP(), []int{3}
}

func (x *GetLEDsResponse) GetStatusLedColor() Color {
	if x != nil {
		return x.StatusLedColor
	}
	return Color_RED
}

func (x *GetLEDsResponse) GetRecLedOn() bool {
	if x != nil {
		return x.RecLedOn
	}
	return false
}

func (x *GetLEDsResponse) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

var File_ioctrl_proto protoreflect.FileDescriptor

const file_ioctrl_proto_rawDesc = "" +
	"\n" +
	"\fioctrl.proto\x12\rcanf22g2.grpc\x1a\x1cgoogle/api/annotations.proto\"\x84\x01\n" +
	"\x0eSetLEDsRequest\x12<\n" +
	"\x0estatusLedColor\x18\x01 \x01(\x0e2\x14.canf22g2.grpc.ColorR\x0estatusLedColor\x12\x1a\n" +
	"\brecLedOn\x18\x02 \x01(\bR\brecLedOn\x12\x18\n" +
	"\achannel\x18\x03 \x01(\x05R\achannel\"+\n" +
	"\x0fSetLEDsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x0eGetLEDsRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\x05R\achannel\"\x85\x01\n" +
	"\x0fGetLEDsResponse\x12<\n" +
	"\x0estatusLedColor\x18\x01 \x01(\x0e2\x14.canf22g2.grpc.ColorR\x0estatusLedColor\x12\x1a\n" +
	"\brecLedOn\x18\x02 \x01(\bR\brecLedOn\x12\x18\n" +
	"\achannel\x18\x03 \x01(\x05R\achannel*\x1b\n" +
	"\x05Color\x12\a\n" +
	"\x03RED\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x012\xc7\x01\n" +
	"\n" +
	"LEDService\x12]\n" +
	"\aSetLEDs\x12\x1d.canf22g2.grpc.SetLEDsRequest\x1a\x1e.canf22g2.grpc.SetLEDsResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/leds\x12Z\n" +
	"\aGetLEDs\x12\x1d.canf22g2.grpc.GetLEDsRequest\x1a\x1e.canf22g2.grpc.GetLEDsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/ledsB\x0fZ\rcanf22g2/grpcb\x06proto3"

var (
	file_ioctrl_proto_rawDescOnce sync.Once
	file_ioctrl_proto_rawDescData []byte
)

func file_ioctrl_proto_rawDescGZIP() []byte {
	file_ioctrl_proto_rawDescOnce.Do(func() {
		file_ioctrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioctrl_proto_rawDesc), len(file_ioctrl_proto_rawDesc)))
	})
	return file_ioctrl_proto_rawDescData
}

var file_ioctrl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ioctrl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ioctrl_proto_goTypes = []any{
	(Color)(0),              // 0: canf22g2.grpc.Color
	(*SetLEDsRequest)(nil),  // 1: canf22g2.grpc.SetLEDsRequest
	(*SetLEDsResponse)(nil), // 2: canf22g2.grpc.SetLEDsResponse
	(*GetLEDsRequest)(nil),  // 3: canf22g2.grpc.GetLEDsRequest
	(*GetLEDsResponse)(nil), // 4: canf22g2.grpc.GetLEDsResponse
}
var file_ioctrl_proto_depIdxs = []int32{
	0, // 0: canf22g2.grpc.SetLEDsRequest.statusLedColor:type_name -> canf22g2.grpc.Color
	0, // 1: canf22g2.grpc.GetLEDsResponse.statusLedColor:type_name -> canf22g2.grpc.Color
	1, // 2: canf22g2.grpc.LEDService.SetLEDs:input_type -> canf22g2.grpc.SetLEDsRequest
	3, // 3: canf22g2.grpc.LEDService.GetLEDs:input_type -> canf22g2.grpc.GetLEDsRequest
	2, // 4: canf22g2.grpc.LEDService.SetLEDs:output_type -> canf22g2.grpc.SetLEDsResponse
	4, // 5: canf22g2.grpc.LEDService.GetLEDs:output_type -> canf22g2.grpc.GetLEDsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ioctrl_proto_init() }
func file_ioctrl_proto_init() {
	if File_ioctrl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioctrl_proto_rawDesc), len(file_ioctrl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ioctrl_proto_goTypes,
		DependencyIndexes: file_ioctrl_proto_depIdxs,
		EnumInfos:         file_ioctrl_proto_enumTypes,
		MessageInfos:      file_ioctrl_proto_msgTypes,
	}.Build()
	File_ioctrl_proto = out.File
	file_ioctrl_proto_goTypes = nil
	file_ioctrl_proto_depIdxs = nil
}
